export const SET_PLAY_LIST = 'SET_PLAY_LIST'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_PLAYING_MODE = 'SET_PLAYING_MODE'
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'

//歌手信息(热门歌曲,专辑，mvs,歌手介绍，相似歌手)
export const SET_SINGER_HOT_SONGS = 'SET_SINGER_HOT_SONGS'
export const SET_SINGER_ALBUMS = 'SET-SINGER_ALBUMS'
export const SET_SINGER_MVS = 'SET_SINGER_MVS'
export const SET_SINGER_DESC = 'SET_SINGER_DESC'
export const SET_SINGER_SIMILAR = 'SET_SINGER_SIMILAR'